<html>
    <head>
        <?=$this->headTitle()?>
        <meta charset='utf-8'>
        <?=$this->headMeta()?>
        <?=$this->headLink()?>
        <?=$this->headScript()?>
    </head>
    <body>
        <h1>Curso Zend</h1>
        <!-- ------------- -->
        <?=$this->layout()->content?>
        <!-- ------------- -->
        </br></br></br></br>
        <hr>
        Footer
    </body>
</html>