<?=$this->doctype()?>
<html>
    <head>
        <?=$this->headTitle()?>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?=$this->headMeta()?>
        <?=$this->headLink()?>
        <?=$this->headScript()?>
    </head>
    <body id="ventas">
        <?=$this->render('_cabecera.phtml');?>
        <?=$this->render('_menu.phtml');?>
        <div id="contenido">
            <?=$this->render('_mensajes.phtml');?>
            <?=$this->layout()->content?>
        </div>
        <?=$this->render('_pie.phtml');?>
</body>
</html>