<h2>Productos:</h2>


<table border="1" class="listado">
    <thead>
        <tr>
            <th>Categoría</th>
            <th>Fabricante</th>
            <th>Nombre</th>
            <th>Precio</th>
            <th>Operaciones</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->productos as $producto): ?>
            <?php $id = $producto['id']; ?>
            <tr class="<?=$producto['activo']?'activo':'inactivo'?>">
                <td><?=$this->escape($producto['categoria'])?></td>
                <td><?=$this->escape($producto['fabricante'])?></td>
                <td><?=$this->escape($producto['nombre'])?></td>
                <td class="num"><?=$producto['precio']?></td>
                <td>

                    <?php $link = $this->url(array('action'=>'ver','id'=>$id)) ?>
                    <a href="<?=$link?>">[Ver]</a>

                    <?php $link = $this->url(array('action'=>'ver','id'=>$id)) ?>
                    <a rel="<?=$id?>" class="verAjax" href="<?=$link?>">[Ver-Ajax]</a>

                    <?php $link = $this->url(array('action'=>'editar','id'=>$id)) ?>
                    <a href="<?=$link?>">[Editar]</a>

                    <?php $link = $this->url(array('action'=>'borrar','id'=>$id)) ?>
                    <a href="<?=$link?>" onclick="return confirm('¿Estás seguro?')">[Borrar]</a>

                    <?php if( $producto['activo'] ): ?>
                        <?php $link = $this->url(array('action'=>'desactivar','id'=>$id)) ?>
                        <a href="<?=$link?>">[Desactivar]</a>
                    <?php else: ?>
                        <?php $link = $this->url(array('action'=>'activar','id'=>$id)) ?>
                        <a href="<?=$link?>">[Activar]</a>
                    <?php endif; ?>

                    <?php $link = $this->url(array('action'=>'ver-pdf','id'=>$id)) ?>
                    <a href="<?=$link?>">[PDF]</a>

                    <?php $link = $this->url(array('action'=>'ver-dom-pdf','id'=>$id)) ?>
                    <a href="<?=$link?>">[DOM-PDF]</a>
                        
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<div class="pagination all">
    <?=$this->paginationControl($this->productos, 'Sliding' ,'producto/_pag.phtml')?>
</div>

<div id="ver-producto" style="border: 1px red solid; width: 500px;">
    
</div>


<a href="<?=$this->url(array('action'=>'nuevo','controller'=>'producto'),null,true)?>">Nuevo</a>


<script type="text/javascript">
    $('.verAjax').click(function(){
        $.ajax(
            {
                'url' : '/producto/ver',
                'data' : {
                    'id' : $(this).attr('rel')
                },
                'success': function(response){
                    $('#ver-producto').html(response);
                },
                'type' : 'get',
                'dateType' : 'html'
            }
        );
        return false;
    });
</script>