<h2>Categorias:</h2>

<? foreach($this->mensajes as $categoria): ?>
        <li><?=$categoria?></li>
<? endforeach; ?>

<a href="<?=$this->url(array('module'=>'ventas','controller'=>'categoria','action'=>'nuevo'),'default',true)?>">Nuevo</a>
<br />
<br />

<table border="1">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Desc</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        <? foreach($this->categorias as $categoria): ?>
        <tr class="<?=$categoria['activo']?'':'in'?>activo">
            <td><?=$categoria['nombre']?></td>
            <td><?=$categoria['descripcion']==''?'&nbsp;':$categoria['descripcion']?></td>
            <td>
                <a href="<?=$this->url(array('module'=>'ventas','controller'=>'categoria','action'=>'editar','id'=>$categoria['id']),'default',true)?>">Editar</a>
                <? if( (bool) $categoria['activo'] ): ?>
                    <a href="<?=$this->url(array('module'=>'ventas','controller'=>'categoria','action'=>'desactivar','id'=>$categoria['id']),'default',true)?>">Desactivar</a>
                <? else: ?>
                    <a href="<?=$this->url(array('module'=>'ventas','controller'=>'categoria','action'=>'activar','id'=>$categoria['id']),'default',true)?>">Activar</a>
                <? endif; ?>
                
            </td>
        </tr>
        <? endforeach; ?>
    </tbody>
</table>

<div class="pagination all">
    <?=$this->paginationControl($this->categorias,'Sliding','categoria/_pag.phtml')?>
</div>


<style type="text/css">
    .inactivo{background-color: lightpink;}
    .activo{background-color: lightgreen;}
</style>
    