<h2>Categorias:</h2>

<a href="<?=$this->url(array('module'=>'ventas','controller'=>'categoria','action'=>'index'),'default',true)?>">Volver</a>
<br />
<br />

<?=$this->form?>

<script type="text/javascript">
    //$();
    
    
    $('#nombre').blur( function(){
        $.ajax( {
            'url' : 'http://asdsad.com/ventas/categoria/valida-categoria',
            'type' : 'get',
            'data' : {
                'nombre':$(this).val()
            },
            'success' : function(response){
                console.log(response);
                var $box = $('#nombre').parent();
                $box.find('.msgajx').remove();
                if(response.status=='OK'){
                    $box.append('<span class="msgajx">todo OK</span>');
                }else{
                    $box.append('<span class="msgajx">ERROR</span>');
                }
            },
            'dataType' : 'json'
        });
    });
    

    
    
    
</script>

<style>
    #nombre{
        border: 1px green dashed;
    }
</style>