<h2>Fabricantes:</h2>


<table border="1" class="listado">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Ruc</th>
            <th>Operaciones</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->fabricantes as $fabricante): ?>
            <?php $id = $fabricante['id']; ?>
            <tr class="<?=$fabricante['activo']?'activo':'inactivo'?>">
                <td><?=$this->escape($fabricante['nombre'])?></td>
                <td><?=$fabricante['ruc']?></td>
                <td>

                    <?php $link = $this->url(array('action'=>'ver','id'=>$id)) ?>
                    <a href="<?=$link?>">[Ver]</a>
                    
                    <?php $link = $this->url(array('slug'=>$fabricante['slug']),'slugfab') ?>
                    <a href="<?=$link?>">[Ver-c/Slug]</a>

                    <?php $link = $this->url(array('action'=>'editar','id'=>$id)) ?>
                    <a href="<?=$link?>">[Editar]</a>

                    <?php $link = $this->url(array('action'=>'borrar','id'=>$id)) ?>
                    <a href="<?=$link?>" onclick="return confirm('¿Estás seguro?')">[Borrar]</a>

                    <?php if( $fabricante['activo'] ): ?>
                        <?php $link = $this->url(array('action'=>'desactivar','id'=>$id)) ?>
                        <a href="<?=$link?>">[Desactivar]</a>
                    <?php else: ?>
                        <?php $link = $this->url(array('action'=>'activar','id'=>$id)) ?>
                        <a href="<?=$link?>">[Activar]</a>
                    <?php endif; ?>
                        
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<br />

<a href="<?=$this->url(array('action'=>'nuevo','controller'=>'fabricante'),null,true)?>">Nuevo</a>
